services:
  n1:
    build: ./n1
    container_name: c1
    ports:
      - "8098:8000"

  n2:
    build: nginx:stable-alpine3.23
    container_name: c2
    ports:
      - "80:80"
      
  n3:
    build: ./n3
    container_name: c3
    depends_on:
      - n1